version: '3'
services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: intimatelook-core
    ports:
      - "5432:5432"
